### ISSUE TITLE
Panic in pkg/component/reconciler.go

### ISSUE THREAD

**Issue by cbarbian-sap** [SAP/component-operator-runtime#160]
A panic happens here:
```json
{"level":"error","ts":"2024-10-15T11:20:38Z","msg":"Observed a panic","controller":"component","controllerGroup":"core.cs.sap.com","controllerKind":"Component","Component":{"name":"cert-manager","namespace":"cs-bootstrap"},"namespace":"cs-bootstrap","name":"cert-manager","reconcileID":"0764938f-2428-4ff7-8e73-5f2c47f2aebf","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 458 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x2d81428, 0xc006737560}, {0x239b8a0, 0x4315a10})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:105 +0x112\npanic({0x239b8a0?, 0x4315a10?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile.func1()\n\t/go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:231 +0x24f\ngithub.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile(0x2db58c0, {0x2d81428, 0xc006737560}, {{{0xc008c373a0, 0xc}, {0xc008c37390, 0xc}}})\n\t/go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:360 +0x1aa7\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0067374d0?, {0x2d81428?, 0xc006737560?}, {{{0xc008c373a0?, 0x0?}, {0xc008c37390?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2d9f920, {0x2d81460, 0xc000238d70}, {{{0xc008c373a0, 0xc}, {0xc008c37390, 0xc}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2d9f920, {0x2d81460, 0xc000238d70})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263 +0x20e\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 47\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:900\ngithub.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile.func1\n\t/go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:231\ngithub.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile\n\t/go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:360\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

The relevant stack is:

```bash
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:900
github.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile.func1
        /go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:231
github.com/sap/component-operator-runtime/pkg/component.(*Reconciler[...]).Reconcile
        /go/pkg/mod/github.com/sap/component-operator-runtime@v0.3.40/pkg/component/reconciler.go:360
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224
```

**Comment by cbarbian-sap** [comment]
It seems that the following statement

```go
if status.State == StateProcessing && now.Sub(status.ProcessingSince.Time) >= timeout {
```

(in https://github.com/SAP/component-operator-runtime/blob/main/pkg/component/reconciler.go#L231) is causing the panic, because `status.ProcessingSince` is `nil` in certain cases. 

The linked PR should fix this.
